/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.bdoo.visao;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import trabalho.bdoo.modelo.Cliente;
import trabalho.bdoo.modelo.Item;
import trabalho.bdoo.modelo.Pedido;

/**
 *
 * @author Dú Máximo
 */
public class VisaoPedido extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    public VisaoPedido() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLblCliente = new javax.swing.JLabel();
        jCmbBoxCliente = new javax.swing.JComboBox();
        jScrollCliente = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        jBtnRemover = new javax.swing.JButton();
        jLblItem = new javax.swing.JLabel();
        jCmbBoxItem = new javax.swing.JComboBox();
        jBtnCadastrar = new javax.swing.JButton();
        jBtnNovo = new javax.swing.JButton();
        jBtnAdicionarItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollItem = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jBtnFiltrar = new javax.swing.JButton();
        jLblItemFiltro = new javax.swing.JLabel();
        jTxtClienteFiltro = new javax.swing.JTextField();
        jLblPrecoFiltro = new javax.swing.JLabel();
        jTxtTotalFiltro = new javax.swing.JTextField();
        jBtnEditar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        jLblCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLblCliente.setText("Cliente:");

        jCmbBoxCliente.setBackground(new java.awt.Color(0, 0, 0));
        jCmbBoxCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCmbBoxCliente.setForeground(new java.awt.Color(255, 255, 255));

        jTableItem.setBackground(new java.awt.Color(102, 102, 102));
        jTableItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        jTableItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableItem.setForeground(new java.awt.Color(255, 255, 255));
        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Preço"
            }
        ));
        jTableItem.setToolTipText("");
        jTableItem.setGridColor(new java.awt.Color(0, 0, 0));
        jTableItem.getTableHeader().setResizingAllowed(false);
        jTableItem.getTableHeader().setReorderingAllowed(false);
        jScrollCliente.setViewportView(jTableItem);

        jBtnRemover.setBackground(new java.awt.Color(0, 0, 0));
        jBtnRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnRemover.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRemover.setText("Remover");

        jLblItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblItem.setForeground(new java.awt.Color(255, 255, 255));
        jLblItem.setText("Item:");

        jCmbBoxItem.setBackground(new java.awt.Color(0, 0, 0));
        jCmbBoxItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCmbBoxItem.setForeground(new java.awt.Color(255, 255, 255));

        jBtnCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCadastrar.setText("Salvar");

        jBtnNovo.setBackground(new java.awt.Color(0, 0, 0));
        jBtnNovo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNovo.setText("Novo Cadastro");

        jBtnAdicionarItem.setBackground(new java.awt.Color(0, 0, 0));
        jBtnAdicionarItem.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdicionarItem.setText("Adicionar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jBtnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnAdicionarItem)))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmbBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAdicionarItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jBtnCadastrar)
                    .addComponent(jBtnNovo)))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Pedido");
        jLabelTitulo.setAutoscrolls(true);
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(0, 0, 0)))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));

        jTablePedido.setBackground(new java.awt.Color(102, 102, 102));
        jTablePedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        jTablePedido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePedido.setForeground(new java.awt.Color(255, 255, 255));
        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Total"
            }
        ));
        jTablePedido.setToolTipText("");
        jTablePedido.setGridColor(new java.awt.Color(0, 0, 0));
        jTablePedido.getTableHeader().setResizingAllowed(false);
        jTablePedido.getTableHeader().setReorderingAllowed(false);
        jScrollItem.setViewportView(jTablePedido);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Filtro de Busca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));

        jBtnFiltrar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnFiltrar.setText("Filtrar");

        jLblItemFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblItemFiltro.setForeground(new java.awt.Color(255, 255, 255));
        jLblItemFiltro.setText("Cliente");

        jLblPrecoFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblPrecoFiltro.setForeground(new java.awt.Color(255, 255, 255));
        jLblPrecoFiltro.setText("Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtnFiltrar)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLblItemFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtClienteFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblPrecoFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTotalFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jBtnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblItemFiltro)
                    .addComponent(jTxtClienteFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPrecoFiltro)
                    .addComponent(jTxtTotalFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBtnEditar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setText("Editar");

        jBtnExcluir.setBackground(new java.awt.Color(0, 0, 0));
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setText("Excluir");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollItem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jBtnEditar)
                        .addGap(152, 152, 152)
                        .addComponent(jBtnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollItem, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionarItem;
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnFiltrar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JComboBox jCmbBoxCliente;
    private javax.swing.JComboBox jCmbBoxItem;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JLabel jLblItem;
    private javax.swing.JLabel jLblItemFiltro;
    private javax.swing.JLabel jLblPrecoFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollCliente;
    private javax.swing.JScrollPane jScrollItem;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JTextField jTxtClienteFiltro;
    private javax.swing.JTextField jTxtTotalFiltro;
    // End of variables declaration//GEN-END:variables

    public void apresentarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public void listarCliente(List<Cliente> lista) {
        jCmbBoxCliente.removeAllItems();

        for (Cliente c : lista) {
            jCmbBoxCliente.addItem(c);
        }
    }

    public void listarItem(List<Item> lista) {
        jCmbBoxItem.removeAllItems();

        for (Item i : lista) {
            jCmbBoxItem.addItem(i);
        }
    }

    public void listarItemPedido(List<Item> lista) {

        DefaultTableModel modelo = (DefaultTableModel) jTableItem.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        int cont = 0;

        for (Item i : lista) {
            modelo.insertRow(cont++, new Object[]{i.getNome(), i.getPreco()});
        }
    }

    public void listarPedido(List<Pedido> lista) {

        DefaultTableModel modelo = (DefaultTableModel) jTablePedido.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        int cont = 0;

        for (Pedido p : lista) {
            modelo.insertRow(cont++, new Object[]{p.getCliente().getNome(), p.getTotal()});
        }
    }

    public String getFiltroCliente() {
        if (jTxtClienteFiltro.getText().equals("")) {
            return null;
        } else {
            return jTxtClienteFiltro.getText();
        }
    }

    public Double getFiltroTotal() {
        if (jTxtTotalFiltro.getText().equals("")) {
            return null;
        } else {
            return Double.parseDouble(jTxtTotalFiltro.getText());
        }
    }

    public JButton getjBtnAdicionarItem() {
        return jBtnAdicionarItem;
    }

    public javax.swing.JButton getjBtnFiltrar() {
        return jBtnFiltrar;
    }

    public javax.swing.JButton getjBtnRemover() {
        return jBtnRemover;
    }

    public javax.swing.JComboBox getjCmbBoxCliente() {
        return jCmbBoxCliente;
    }

    public javax.swing.JScrollPane getjScrollItem() {
        return jScrollItem;
    }

    public javax.swing.JTextField getjTxtItemFiltro() {
        return jTxtClienteFiltro;
    }

    public javax.swing.JTextField getjTxtPrecoFiltro() {
        return jTxtTotalFiltro;
    }

    public JButton getjBtnCadastrar() {
        return jBtnCadastrar;
    }

    public JButton getjBtnNovo() {
        return jBtnNovo;
    }

    public JButton getjBtnEditar() {
        return jBtnEditar;
    }

    public JButton getjBtnExcluir() {
        return jBtnExcluir;
    }

    public JTable getjTableItem() {
        return jTableItem;
    }

    public JTable getjTablePedido() {
        return jTablePedido;
    }

    public JComboBox getjCmbBoxItem() {
        return jCmbBoxItem;
    }

    public JScrollPane getjScrollCliente() {
        return jScrollCliente;
    }

}
